[build.environment]
MY_API_KEY = "your_api_key"
MONGODB_URI = 'mongodb+srv://davtekdon:AUnzhsuBMMrn0yV1@boundless.szd1u.mongodb.net/?retryWrites=true&w=majority&appName=boundless'
API_BASE_URL = 'https://boundlessbolt.netlify.app'
